-- Seed policies (10 random policies)
INSERT INTO policies (id, user_id, file_name, insurer, plan_name, sum_insured, premium, policy_type, policy_year, age, exclusions, waiting_periods, sub_limits, copay, no_claim_bonus, restoration, network_hospitals, cashless_hospitals, features, rating, summary, analysis_date, raw_data)
VALUES
  (gen_random_uuid(), 'user_001', 'Health_MAX_2024.pdf', 'Star Health', 'Star Comprehensive', 500000, 25000, 'Individual', 2024, 35, ARRAY['Cosmetic surgeries'], '{"ped": 2, "initial": 30, "specific": 0, "maternity": 36}'::jsonb, '{"room_rent": "1500/day", "icu": "3000/day"}'::jsonb, 10, 50, 'Yes', 5000, ARRAY['AYUSH coverage', 'Free health checkups'], 4, 'Comprehensive health cover with decent network', '2024-01-15', '{"pdf_size": "2.3MB"}'::jsonb),
  (gen_random_uuid(), 'user_002', 'Care_Plus_Policy.pdf', 'Care Health', 'Care Plus', 750000, 32000, 'Family Floater', 2024, 42, ARRAY['Dental treatments'], '{"ped": 3, "initial": 30, "specific": 0, "maternity": 48}'::jsonb, '{"room_rent": "2000/day"}'::jsonb, 0, 60, 'No', 7500, ARRAY['Maternity after 3 years', 'OPD cover'], 3, 'Good family policy but limited room rent', '2024-02-10', '{"pdf_size": "1.8MB"}'::jsonb),
  (gen_random_uuid(), 'user_003', 'ICICI_Prudent.pdf', 'ICICI Lombard', 'Prudent Health', 1000000, 45000, 'Individual', 2023, 28, ARRAY['Infertility treatments'], '{"ped": 1, "initial": 30, "specific": 0, "maternity": 24}'::jsonb, '{"room_rent": "2500/day", "icu": "4000/day", "pre_post_hospitalization": "60 days"}'::jsonb, 5, 70, 'Yes', 10000, ARRAY['Global coverage', 'Second opinion'], 5, 'Premium policy with excellent coverage', '2023-11-05', '{"pdf_size": "3.1MB"}'::jsonb),
  (gen_random_uuid(), 'user_004', 'HDFC_ERGO_Optima.pdf', 'HDFC ERGO', 'Optima Secure', 2000000, 68000, 'Family Floater', 2024, 50, ARRAY['Weight loss surgeries'], '{"ped": 2, "initial": 30, "specific": 0, "maternity": 36}'::jsonb, '{"room_rent": "No_sub_limit", "icu": "No_sub_limit"}'::jsonb, 0, 75, 'Yes', 15000, ARRAY['No room rent limit', 'Unlimited sum insured'], 4, 'Excellent for senior citizens', '2024-03-20', '{"pdf_size": "2.7MB"}'::jsonb),
  (gen_random_uuid(), 'user_005', 'Bajaj_Allianz_Pro.pdf', 'Bajaj Allianz', 'Pro Team Plus', 1500000, 52000, 'Individual', 2023, 40, ARRAY['Hearing aids'], '{"ped": 2, "initial": 30, "specific": 0, "maternity": "Not covered"}'::jsonb, '{"room_rent": "1800/day", "ambulance": "2000"}'::jsonb, 10, 55, 'Yes', 8000, ARRAY['Critical illness rider', 'Personal accident'], 3, 'Decent value for money', '2023-09-12', '{"pdf_size": "2.5MB"}'::jsonb),
  (gen_random_uuid(), 'user_001', ' Religare_Care.pdf', 'Care Health', 'Care Supreme', 3000000, 95000, 'Family Floater', 2024, 38, ARRAY[], '{"ped": 1, "initial": 30, "specific": 0, "maternity": 24}'::jsonb, '{"room_rent": "Unlimited", "icu": "Unlimited"}'::jsonb, 0, 80, 'Yes', 20000, ARRAY['Super top-up', 'Maternity cover'], 5, 'Super top-up policy with unlimited room rent', '2024-04-01', '{"pdf_size": "2.9MB"}'::jsonb),
  (gen_random_uuid(), 'user_003', 'TATA_AIG_MediCare.pdf', 'TATA AIG', 'MediCare Premier', 800000, 38000, 'Individual', 2023, 45, ARRAY['Experimental treatments'], '{"ped": 3, "initial": 45, "specific": 0, "maternity": "Not covered"}'::jsonb, '{"room_rent": "1600/day"}'::jsonb, 15, 45, 'No', 6500, ARRAY['Domiciliary hospitalization', 'Road ambulance'], 2, 'Basic policy with long waiting periods', '2023-07-22', '{"pdf_size": "2.1MB"}'::jsonb),
  (gen_random_uuid(), 'user_006', 'New_India_Assurance.pdf', 'New India Assurance', 'National Mediclaim', 500000, 18000, 'Individual', 2024, 29, ARRAY['HIV/AIDS treatments'], '{"ped": 4, "initial": 30, "specific": 0, "maternity": 48}'::jsonb, '{"room_rent": "1200/day"}'::jsonb, 20, 40, 'No', 4000, ARRAY['Pre-and-post hospitalization', 'AYUSH treatments'], 2, 'Economy option with basic coverage', '2024-01-08', '{"pdf_size": "1.5MB"}'::jsonb),
  (gen_random_uuid(), 'user_002', 'United_India_Protect.pdf', 'United India', 'Family Protect', 1200000, 48000, 'Family Floater', 2023, 33, ARRAY['Gender reassignment'], '{"ped": 2, "initial": 30, "specific": 0, "maternity": 36}'::jsonb, '{"room_rent": "1900/day", "disease_wise": {"cataract": "20000"}}'::jsonb, 5, 65, 'Yes', 9000, ARRAY['Daily cash allowance', 'Health checkups'], 3, 'Mid-range family policy with sub-limits', '2023-12-03', '{"pdf_size": "2.2MB"}'::jsonb),
  (gen_random_uuid(), 'user_004', 'Oriental_Privilege.pdf', 'Oriental Insurance', 'Privilege Health', 2500000, 72000, 'Individual', 2024, 55, ARRAY['Congenital diseases'], '{"ped": 1, "initial": 30, "specific": 12, "maternity": 24}'::jsonb, '{"room_rent": "2200/day", "icu": "4500/day", "pre_post_hospitalization": "90 days"}'::jsonb, 0, 72, 'Yes', 12000, ARRAY['Organ donor expenses', 'Reconstruction surgery'], 4, 'Good for elderly with specific illness cover', '2024-02-28', '{"pdf_size": "2.8MB"}'::jsonb);

-- Seed claims (8 random claims)
INSERT INTO claims (id, user_id, policy_id, treatment, hospital, amount, status, win_probability, expected_amount, analysis)
VALUES
  (gen_random_uuid(), 'user_001', (SELECT id FROM policies WHERE file_name = 'Health_MAX_2024.pdf' LIMIT 1), 'Appendectomy', 'Apollo Hospitals, Chennai', 85000, 'approved', 92, '₹85,000', '{"covered": true, "loopholes": ["Pre-authorization obtained"], "documents_needed": ["Surgical report", "Bills"]}'::jsonb),
  (gen_random_uuid(), 'user_002', (SELECT id FROM policies WHERE file_name LIKE '%Care_Plus%' LIMIT 1), 'Cataract Surgery', 'LV Prasad Eye Institute, Hyderabad', 125000, 'pending', 78, '₹1.0L - ₹1.2L', '{"covered": true, "sub_limit_applies": true, "loopholes": ["Room rent sub limit exceeded by ₹5000"]}'::jsonb),
  (gen_random_uuid(), 'user_003', (SELECT id FROM policies WHERE file_name = 'ICICI_Prudent.pdf' LIMIT 1), 'Angioplasty', 'Fortis Escorts, Delhi', 280000, 'approved', 95, '₹2.8L', '{"covered": true, "waiting_period_ok": true, "critical_illness_rider_applicable": true}'::jsonb),
  (gen_random_uuid(), 'user_004', (SELECT id FROM policies WHERE file_name LIKE '%HDFC_ERGO%' LIMIT 1), 'Knee Replacement', 'Kokilaben Hospital, Mumbai', 450000, 'pending', 88, '₹4.2L - ₹4.5L', '{"covered": true, "prosthesis_limit": "₹50,000", "loopholes": ["Prosthesis cost will be partially covered"]}'::jsonb),
  (gen_random_uuid(), 'user_005', (SELECT id FROM policies WHERE file_name = 'Bajaj_Allianz_Pro.pdf' LIMIT 1), 'Chemotherapy', 'Tata Memorial, Mumbai', 650000, 'rejected', 35, 'N/A', '{"covered": false, "reasons": ["Pre-existing cancer diagnosis - 4 months ago, waiting period not served"], "loopholes": ["Check IRDAI moratorium provisions", "Can appeal to ombudsman"]}'::jsonb),
  (gen_random_uuid(), 'user_001', (SELECT id FROM policies WHERE file_name LIKE '%Supreme%' LIMIT 1), 'Dental Implant', 'Clove Dental, Bangalore', 45000, 'pending', 65, '₹20,000 - ₹30,000', '{"covered": false, "reasons": ["Dental treatments explicit exclusion"], "alternate_argument": ["Emergency dental procedure after accident - may consider"]}'::jsonb),
  (gen_random_uuid(), 'user_006', (SELECT id FROM policies WHERE file_name = 'New_India_Assurance.pdf' LIMIT 1), 'Gallbladder Surgery', 'Sakra Hospital, Bangalore', 145000, 'pending', 82, '₹1.3L - ₹1.4L', '{"covered": true, "pre_post_hospitalization_covered": 30, "loopholes": ["Cashless facility may not be available - need reimbursement"]}'::jsonb),
  (gen_random_uuid(), 'user_002', (SELECT id FROM policies WHERE file_name = 'United_India_Protect.pdf' LIMIT 1), 'Maternity - Normal Delivery', 'Manipal Hospital, Delhi', 120000, 'pending', 95, '₹1.1L - ₹1.2L', '{"covered": true, "waiting_period_served": true, "sub_limit_check": "Maternity cover limit usually ₹50,000 - may have shortfall", "documents_needed": ["Marriage certificate", "Delivery records"]}'::jsonb);

-- Seed chat_history (15 random messages)
INSERT INTO chat_history (id, user_id, role, content, policy_ids)
VALUES
  (gen_random_uuid(), 'user_001', 'user', 'What is the waiting period for pre-existing diseases?', ARRAY[(SELECT id FROM policies WHERE file_name = 'Health_MAX_2024.pdf' LIMIT 1)]),
  (gen_random_uuid(), 'user_001', 'assistant', 'The waiting period for Pre-Existing Diseases (PED) in your Star Health Comprehensive policy is 2 years. This means claims related to conditions diagnosed within 2 years before policy inception will not be covered.', ARRAY[(SELECT id FROM policies WHERE file_name = 'Health_MAX_2024.pdf' LIMIT 1)]),
  (gen_random_uuid(), 'user_002', 'user', 'Is maternity covered in my Care Plus policy?', ARRAY[(SELECT id FROM policies WHERE file_name LIKE '%Care_Plus%' LIMIT 1)]),
  (gen_random_uuid(), 'user_002', 'assistant', 'Maternity is covered after a waiting period of 48 months (4 years) in your Care Plus policy. Please check if your policy has completed this waiting period.', ARRAY[(SELECT id FROM policies WHERE file_name LIKE '%Care_Plus%' LIMIT 1)]),
  (gen_random_uuid(), 'user_003', 'user', 'How do I file a claim for my angioplasty?', ARRAY[(SELECT id FROM policies WHERE file_name = 'ICICI_Prudent.pdf' LIMIT 1)]),
  (gen_random_uuid(), 'user_003', 'assistant', '1. Pre-authorize: Call ICICI Lombard 48 hours before procedure (for planned) or within 24 hours (emergency).
2. Documents: Hospital bills, discharge summary, booking confirmation, ID proof, policy copy.
3. Submit: Online portal or at hospital TPA desk ( Medi Assist).
4. Track: Use claim ID within 7-10 working days.', ARRAY[(SELECT id FROM policies WHERE file_name = 'ICICI_Prudent.pdf' LIMIT 1)]),
  (gen_random_uuid(), 'user_004', 'user', 'What is the room rent limit?', ARRAY[(SELECT id FROM policies WHERE file_name LIKE '%HDFC_ERGO%' LIMIT 1)]),
  (gen_random_uuid(), 'user_004', 'assistant', 'Excellent news! Your HDFC ERGO Optima Secure policy has NO SUB-LIMIT on room rent. You can choose any room category without worrying about daily caps, which is one of the best features of this policy.', ARRAY[(SELECT id FROM policies WHERE file_name LIKE '%HDFC_ERGO%' LIMIT 1)]),
  (gen_random_uuid(), 'user_005', 'user', 'Why was my chemotherapy claim rejected?', ARRAY[(SELECT id FROM policies WHERE file_name = 'Bajaj_Allianz_Pro.pdf' LIMIT 1)]),
  (gen_random_uuid(), 'user_005', 'assistant', 'Your claim was rejected because the cancer diagnosis was made 4 months ago, and your policy has a 24-month waiting period for pre-existing diseases. However, you can consider:
1. IRDAI moratorium after 8 years continuous coverage (check if applicable)
2. File grievance with insurance ombudsman within 1 year
3. Get detailed medical opinion and re-submit with new evidence', ARRAY[(SELECT id FROM policies WHERE file_name = 'Bajaj_Allianz_Pro.pdf' LIMIT 1)]),
  (gen_random_uuid(), 'user_001', 'user', 'Is cosmetic surgery covered?', ARRAY[(SELECT id FROM policies WHERE file_name = 'Health_MAX_2024.pdf' LIMIT 1)]),
  (gen_random_uuid(), 'user_001', 'assistant', 'Cosmetic or aesthetic surgeries are explicitly excluded in your Star Health policy, unless they are medically necessary (e.g., post-accident reconstructive surgery). Pure cosmetic procedures like rhinoplasty, liposuction, or facelifts are not covered.', ARRAY[(SELECT id FROM policies WHERE file_name = 'Health_MAX_2024.pdf' LIMIT 1)]),
  (gen_random_uuid(), 'user_006', 'user', 'What is my sum insured?', ARRAY[(SELECT id FROM policies WHERE file_name = 'New_India_Assurance.pdf' LIMIT 1)]),
  (gen_random_uuid(), 'user_006', 'assistant', 'Your New India Assurance National Mediclaim policy has a sum insured of ₹5,00,000 (5 lakhs). This is the maximum amount the insurer will pay for covered medical expenses during the policy year.', ARRAY[(SELECT id FROM policies WHERE file_name = 'New_India_Assurance.pdf' LIMIT 1)]),
  (gen_random_uuid(), 'user_002', 'user', 'Compare my two policies - Care Plus and United India', ARRAY[(SELECT id FROM policies WHERE file_name LIKE '%Care_Plus%' LIMIT 1), (SELECT id FROM policies WHERE file_name = 'United_India_Protect.pdf' LIMIT 1)]),
  (gen_random_uuid(), 'user_002', 'assistant', 'Care Plus: ₹7.5L sum insured, 4-year PED, 4-year maternity, ₹5000 room rent/day
United India: ₹12L sum insured, 2-year PED, 3.5 year maternity, ₹1900 room rent/day + disease sub-limit for cataract (₹20,000)
Recommendation: Care Plus offers higher sum and better room rent, but United India has shorter waiting. Depends on your priority.', ARRAY[(SELECT id FROM policies WHERE file_name LIKE '%Care_Plus%' LIMIT 1), (SELECT id FROM policies WHERE file_name = 'United_India_Protect.pdf' LIMIT 1)]),
  (gen_random_uuid(), 'user_003', 'user', 'Should I buy a top-up policy?', ARRAY[(SELECT id FROM policies WHERE file_name = 'ICICI_Prudent.pdf' LIMIT 1)]),
  (gen_random_uuid(), 'user_003', 'assistant', 'Considering your ₹10L ICICI Prudent policy, a super top-up of ₹25L with deductible of ₹10L would cost ~₹8,000/year and give you coverage up to ₹35L total. Good if you want protection against high-cost treatments (cancer, transplants). Also check if your employer group policy provides additional cover.', ARRAY[(SELECT id FROM policies WHERE file_name = 'ICICI_Prudent.pdf' LIMIT 1)]),
  (gen_random_uuid(), 'user_004', 'user', 'Can I add my parents to my existing policy?', ARRAY[(SELECT id FROM policies WHERE file_name LIKE '%HDFC_ERGO%' LIMIT 1)]),
  (gen_random_uuid(), 'user_004', 'assistant', 'Currently your HDFC ERGO Optima Secure is an individual policy. To add parents:
1. Buy a separate senior citizen policy (easier)
2. Or convert to family floater at renewal (may require fresh underwriting)
3. Or buy a separate top-up for them
Note: Add before any illness diagnosis for best coverage.', ARRAY[(SELECT id FROM policies WHERE file_name LIKE '%HDFC_ERGO%' LIMIT 1)]),
  (gen_random_uuid(), 'user_005', 'user', 'What documents are needed for OPD?', ARRAY[(SELECT id FROM policies WHERE file_name = 'Bajaj_Allianz_Pro.pdf' LIMIT 1)]),
  (gen_random_uuid(), 'user_005', 'assistant', 'For OPD claim (if covered):
1. Original consultation bills
2. Doctor prescription
3. Investigation reports
4. Payment proof
5. Policy copy
Note: Many policies exclude OPD or have limits. Check your Bajaj Allianz Pro - it covers limited OPD up to ₹5000/year.', ARRAY[(SELECT id FROM policies WHERE file_name = 'Bajaj_Allianz_Pro.pdf' LIMIT 1)]),
  (gen_random_uuid(), 'user_001', 'user', 'What is restoration benefit?', ARRAY[(SELECT id FROM policies WHERE file_name = 'Health_MAX_2024.pdf' LIMIT 1)]),
  (gen_random_uuid(), 'user_001', 'assistant', 'Restoration means if you exhaust your sum insured during the policy year, the insurer replenishes it to the original amount (once or multiple times). Your Star Health policy offers restoration. Example: If you use ₹5L from ₹5L cover, you get another ₹5L for new illnesses in same year.', ARRAY[(SELECT id FROM policies WHERE file_name = 'Health_MAX_2024.pdf' LIMIT 1)]);
